name: Test, Deploy, Publish


on: [push]

jobs:
  pytest:
    # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          pytest .


  deploy:
    # https://github.com/marketplace/actions/ssh-remote-commands
    # with inspiration (but different aproach) from: https://maximorlov.com/automate-your-docker-deployments/
    # We will build the image on the remote machine
    needs: pytest
    runs-on: ubuntu-latest
    steps:
      - name: Commands over SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script_stop: true
          script: |
            cd ~/example_project
            git pull
            docker-compose up -d --build
            echo "Successfully deployed, hooray!"

# Publish image: TODO
